let value1 = "3";
let value3 = 1;
console.log(value1 > value3);
console.log("1" == 1);
console.log("1" === 1);
console.log("1" == true);
console.log("0" == false);
console.log("1" === true);
console.log(1 == true);
console.log("1" == 1);
